apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-setup
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: elasticsearch-setup
        image: alpine:3.18
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache curl jq && sh /scripts/setup-script.sh
        env:
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password
        volumeMounts:
        - name: templates-volume
          mountPath: /templates
        - name: scripts-volume
          mountPath: /scripts
      volumes:
      - name: templates-volume
        configMap:
          name: elasticsearch-templates
          items:
          - key: elasticsearch-otel-templates.json
            path: elasticsearch-otel-templates.json
      - name: scripts-volume
        configMap:
          name: elasticsearch-templates
          items:
          - key: setup-script.sh
            path: setup-script.sh
            mode: 0755
