apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-nginx-proxy-config
data:
  nginx.conf: |
    server {
      listen 80;
      
      location / {
          proxy_pass https://elasticsearch-master:9200;
          proxy_ssl_verify off;
          # Base64 encoded elastic:changeme (default Elastic password)
          proxy_set_header Authorization "Basic ZWxhc3RpYzpjaGFuZ2VtZQ==";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-nginx-proxy
  labels:
    app: elasticsearch-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-nginx-proxy
  template:
    metadata:
      labels:
        app: elasticsearch-nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: elasticsearch-nginx-proxy-config # Uses elastic:changeme (default); change for production!ig
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nginx-proxy
spec:
  selector:
    app: elasticsearch-nginx-proxy
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
